TTH-3: created navbar component
Codubee/PetFinderTTH1-2 pull request #3
Opened 2021-03-23 17:56 UTC by areebakq

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
New feature: a navbar component with links to Home and Match pages.

* **What is the current behavior?What does the code do before you made the new changes?** 
Currently, there is only the Landing Page component displayed.

* **What is the new behavior?**
A new navigation bar is added with links to Home and Match. It also has a toggle option for smaller sized screens.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No breaking change.

* **Other information**:
The navbar is not styled for the current color scheme yet.

2021-03-23 18:36 UTC, thomasabigail commented on frontend/src/components/Navbar.js
> +export default NavBar;
Potentially add a newline

2021-03-23 18:37 UTC, thomasabigail commented on frontend/src/components/Navbar.js
> +export default NavBar;
Potentially add a new line?

2021-03-23 19:25 UTC, roseyume reviewed
Remove the link and tagline. You could also add styling. Other than that, it looks good.

2021-03-23 19:25 UTC, roseyume commented on frontend/src/components/Navbar.js
> +          <NavbarText>Tagline</NavbarText>
Remove TagLine

2021-03-23 19:25 UTC, roseyume commented on frontend/src/components/Navbar.js
> +        <NavbarBrand href="/">Pet Finder</NavbarBrand>
Remove link for NavbarBrand PetFinder

2021-03-23 19:59 UTC, Codubee commented on frontend/src/components/Navbar.js
> +const NavBar = (props) => {
Can you change this into a functional component instead of a const please. [Here](https://imgur.com/CO0B4U6) is an example of how to do so.

2021-03-23 20:00 UTC, Codubee requested changes
Great work Areeba! I left some comments for discussion.

2021-03-25 16:31 UTC, Codubee approved these changes
Great job Areeba!

2021-03-25 16:32 UTC, merged