TTH-6 added styling to navbar
Codubee/PetFinderTTH1-2 pull request #7
Opened 2021-03-30 16:40 UTC by areebakq

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Changed color and text style of navbar, added hover styling, pushed Brand text to end.

* **What is the current behavior?What does the code do before you made the new changes?** 
Currently the navbar is not styled to the appropriate color of our website.

* **What is the new behavior?**
The new navbar will be fully styled.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)
No breaking change.

* **Other information**:

2021-03-30 18:22 UTC, thomasabigail commented on frontend/src/styles/Navbar.css
> +}
Maybe add a newline here

2021-03-30 19:18 UTC, roseyume requested changes
Use variable colors from App.css so that color scheming is cohesive. Add new colors to App.css as well for others to use.

2021-03-30 19:18 UTC, roseyume commented on frontend/src/styles/Navbar.css
> +    background-color: #ECF87F;
The color scheme for the website is defined in App.css. You can just call it with var(--easterYellow) to make things cohesive.

2021-03-30 19:18 UTC, roseyume commented on frontend/src/styles/Navbar.css
> +    background-color: #f4fda2;
This shade looks great on top of the easter yellow. You should add it to App.css as a variable so that it can be reused in other components.

2021-03-30 19:18 UTC, roseyume commented on frontend/src/styles/Navbar.css
> +    background-color: #ECF87F;
Also might just be me, but I think the white looked better on than the easter yellow for the navbar.

2021-04-01 18:05 UTC, thomasabigail commented on frontend/src/App.css
>    }
Sorry for being nitpicky, but this needs a newline as well.

2021-04-02 20:53 UTC, Codubee approved these changes

2021-04-02 20:53 UTC, merged